### ISSUE TITLE
Criar estrutura para o composer

### ISSUE THREAD

**Issue by Dovyski** [ccuffs/auth-iduffs#1]
Criar uma estrutura mínima para esse repositório funcionar como um pacote do composer. Utilizar a classe [App/Helpers/AuthHelper.php](https://raw.githubusercontent.com/ccuffs/sac/master/App/Helpers/AuthHelper.php) do [sac](https://github.com/ccuffs/sac).

**Comment by wuerges** [comment]
É uma má ideia usar esse mecanismo porque a senha e o login trafegam em claro pela rede.
O pessoal do @iduffs deveria disponibilizar uma api para isso.

**Comment by Dovyski** [comment]
O login é feito através do id.uffs.edu.br com conexão HTTPS. Nenhuma
credencial trafega pela rede sem criptografia.

>
O único ponto ruim da nossa implementação é que podemos guardar o usuário e
senha sem autorização do usuário. Até que a TI crie uma API, eu acho que
precisamos desse pacote.

**Comment by mateusKoppe** [comment]
Esse ponto negativo que teríamos criando uma biblioteca em PHP (ou qualquer outra linguagem) seria o mesmo que teríamos utilizando um API, nada impede quem implementa uma aplicação que utiliza uma API armazenar a senha e login do usuário antes de mandar para a API, a menos que seja redirecionado para um serviço onde usuário faz o login e então o serviço redireciona o usuário para uma rota de callback com um token de acesso, dessa forma qualquer implementação que utilize esse serviço não tera contato algum com login ou senha.

**Comment by wuerges** [comment]
É isso mesmo que precisa, Mateus. É o primeiro passo pra podermos desenvolver um ecosistema de TI ao redor da UFFS.

**Comment by Dovyski** [comment]
A estrutura inicial do composer está criada, então vou fechar essa issue. Os próximos passos são para evoluirmos os sistemas de autenticação usando essa lib, por exemplo, implementando o que o @wuerges comentou.
